sudo: true
language: generic

matrix:
  include:
    - os: linux
      env: VARIANT=flatpak
      dist: bionic
      arch: ppc64le

env:
  global:
    - WINEPREFIX=~/.winelaz
    - DISPLAY=:99.0

before_install:
  - tools/travis/before_install.sh

install:
  - tools/travis/install.sh

script:
  - tools/travis/build.sh

cache:
  bundler: false
  directories:
    - dists/linux/prefix
